# Generated by Django 3.1.1 on 2022-12-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('jerseynumber', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('strikerate', models.FloatField()),
                ('runs', models.IntegerField()),
            ],
        ),
    ]
